export const ZANO_ASSET_ID = 'd6329b5b1f7c0805b5c345f4957554002a2f557845f64d7645dae0e051a6498a';
export const BANDIT_ASSET_ID = '55a8e0a730b133fb83915ba0e4335a680ae9d07a99642b17774460560f3b003d';
export const WETH_ASSET_ID = '93da681503353509367e241cda3234299dedbbad9ec851de31e900490807bf0c';
export const WBTC_ASSET_ID = '040a180aca4194a158c17945dd115db42086f6f074c1f77838621a4927fffa91';

export const WALLET_MIXIN = {
	DEFAULT: 15,
	AUDITABLE: 0,
};

export const WATCH_ONLY_BLOCKED_REQUESTS = [
	'REQUEST_ACCESS',
	'SEND_TRANSFER',
	'TRANSFER',
	'FINALIZE_TRANSFER_REQUEST',
	'IONIC_SWAP',
	'FINALIZE_IONIC_SWAP_REQUEST',
	'IONIC_SWAP_ACCEPT',
	'FINALIZE_ACCEPT_IONIC_SWAP_REQUEST',
	'BURN_ASSET',
	'FINALIZE_BURN_ASSET_REQUEST',
	'CREATE_ALIAS',
	'FINALIZE_ALIAS_CREATE',
	'REGISTER_ALIAS',
	'UPDATE_ALIAS',
	'REQUEST_MESSAGE_SIGN',
	'FINALIZE_MESSAGE_SIGN',
	'ASSETS_WHITELIST_ADD',
	'FINALIZE_ASSETS_WHITELIST_ADD_REQUESTS',
];

// requests that can only be made by the extension frontend
export const SELF_ONLY_REQUESTS = [
	'SET_API_CREDENTIALS',
	'VALIDATE_CONNECT_KEY',
	'GET_PASSWORD',
	'GET_SIGN_REQUESTS',
	'FINALIZE_MESSAGE_SIGN',
	'GET_IONIC_SWAP_REQUESTS',
	'GET_ALIAS_CREATE_REQUESTS',
	'FINALIZE_IONIC_SWAP_REQUEST',
	'GET_ACCEPT_IONIC_SWAP_REQUESTS',
	'FINALIZE_ACCEPT_IONIC_SWAP_REQUEST',
	'FINALIZE_ALIAS_CREATE',
	'SET_PASSWORD',
	'SEND_TRANSFER',
	'PING_WALLET',
	'SET_ACTIVE_WALLET',
	'GET_WALLETS',
	'FINALIZE_TRANSFER_REQUEST',
	'GET_ASSETS_WHITELIST_ADD_REQUESTS',
	'FINALIZE_ASSETS_WHITELIST_ADD_REQUESTS',
	'GET_BURN_ASSET_REQUESTS',
	'FINALIZE_BURN_ASSET_REQUEST',
	'GET_TRANSFER_REQUEST',
	'REGISTER_ALIAS',
	'UPDATE_ALIAS',
	'GET_ALIAS_BY_ADDRESS',
	'GET_ACCESS_REQUESTS',
	'FINALIZE_REQUEST_ACCESS',
];

export const METHOD_EXTRA_PERMISSIONS: Record<string, string[]> = {
	GET_WALLET_BALANCE: ['balance'],
};

export const PUBLIC_METHODS = ['REQUEST_ACCESS', 'GET_PERMISSIONS'];

export const PASSWORD_HASH_SALT_STORAGE_KEY = 'salt2';
export const PASSWORD_HASH_STORAGE_KEY = 'hash2';

export const PASSWORD_HASH_STORAGE_KEY_DEPRECATED = 'hash';
